include:
  - template: Auto-DevOps.gitlab-ci.yml


Docker Hub:
  stage: deploy
  image: docker
  services:
    - name: docker:dind
      command: [ "--experimental" ]

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --squash -t lthn/build:release-3.1.0 .
    - docker push "lthn/build:release-3.1.0"
  environment:
    name: docker.io
  only:
    - release-3.1.0

